export enum CustomScenarioType {
   Maid = 'maid',
   Nurse = 'nurse',
   Secretary = 'secretary',
   ExGirlfriend = 'ex-girlfriend',
   Influencer = 'influencer',
   StepSister = 'step-sister',
   StepMom = 'step-mom',
   Pornstar = 'pornstar',
   Teacher = 'teacher',
   Lifeguard = 'lifeguard',
   Stripper = 'stripper',
   FitnessCoach = 'fitness-coach',
   Streamer = 'streamer',
   CountryGirl = 'country-girl',
   FlightAttendant = 'flight-attendant',
   PoliceOfficer = 'police-officer',
   CEO = 'ceo',
   Student = 'student',
}